env:
  global:
    - TMPDIR=/tmp
    - RAKUDO_PKG_URL=https://github.com/nxadm/rakudo-pkg/releases/download/v2019.03.1/rakudo-pkg-Debian9_2019.03.1-01_amd64.deb

# https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-without-an-APT-Repository
before_install:
  - cd ${TMPDIR}
  # https://github.com/nxadm/rakudo-pkg
  - wget -O rakudo-pkg.deb ${RAKUDO_PKG_URL}
  - sudo dpkg -i rakudo-pkg.deb
  - export PATH=$PATH:~/.perl6/bin:/opt/rakudo-pkg/bin
  # https://github.com/ugexe/zef
  - git clone https://github.com/ugexe/zef.git && cd zef && perl6 -Ilib bin/zef install .
  - wget -O https://github.com/antoniogamiz/Perl6-Documentable/archive/v1.1.2.tar.gz
  - tar -xvzf v1.1.2.tar.gz
  - zef install ./v1.1.2

install:
  - cd ${TRAVIS_BUILD_DIR}
  - zef --debug --depsonly install .

script:
  - prove -v -r -e "perl6 --ll-exception -Ilib" t